In [2]:
import numpy as np
import math

evals = [-1, 1, 4, 9, 16]
evals = np.array(evals)
omegas = np.sqrt(evals)
omegas

C:\Users\15179\.conda\envs\modaldemo\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


array([nan,  1.,  2.,  3.,  4.])

In [27]:
ksi = (1 + 2*evals) / 2 / omegas
ksi

array([       nan, 1.5       , 2.25      , 3.16666667, 4.125     ])

In [29]:
delta = 1 - ksi * ksi
delta

array([         nan,  -1.25      ,  -4.0625    ,  -9.02777778,
       -16.015625  ])

In [30]:
theta = np.sqrt(delta)

C:\Users\15179\.conda\envs\modaldemo\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [28]:
omegas_d = omegas * np.sqrt(1 - ksi * ksi)

C:\Users\15179\.conda\envs\modaldemo\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [18]:
mat = np.arange(6).reshape((2,3))
print(mat)
vec1 = np.arange(2)
vec1

[[0 1 2]
 [3 4 5]]


array([0, 1])

In [20]:
mat = np.zeros((2, 3))
mat

array([[0., 0., 0.],
       [0., 0., 0.]])